// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: go_wallet_manage_svr.proto

package go_wallet_manage_svr

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GoWalletManageSvrClient is the client API for GoWalletManageSvr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoWalletManageSvrClient interface {
	// 创建钱包
	CreateWallet(ctx context.Context, in *CreateWalletReq, opts ...grpc.CallOption) (*CreateWalletRsp, error)
	// 导入钱包
	ImportWallet(ctx context.Context, in *ImportWalletReq, opts ...grpc.CallOption) (*ImportWalletRsp, error)
}

type goWalletManageSvrClient struct {
	cc grpc.ClientConnInterface
}

func NewGoWalletManageSvrClient(cc grpc.ClientConnInterface) GoWalletManageSvrClient {
	return &goWalletManageSvrClient{cc}
}

func (c *goWalletManageSvrClient) CreateWallet(ctx context.Context, in *CreateWalletReq, opts ...grpc.CallOption) (*CreateWalletRsp, error) {
	out := new(CreateWalletRsp)
	err := c.cc.Invoke(ctx, "/go_wallet_manage_svr.go_wallet_manage_svr/CreateWallet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goWalletManageSvrClient) ImportWallet(ctx context.Context, in *ImportWalletReq, opts ...grpc.CallOption) (*ImportWalletRsp, error) {
	out := new(ImportWalletRsp)
	err := c.cc.Invoke(ctx, "/go_wallet_manage_svr.go_wallet_manage_svr/ImportWallet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoWalletManageSvrServer is the server API for GoWalletManageSvr service.
// All implementations should embed UnimplementedGoWalletManageSvrServer
// for forward compatibility
type GoWalletManageSvrServer interface {
	// 创建钱包
	CreateWallet(context.Context, *CreateWalletReq) (*CreateWalletRsp, error)
	// 导入钱包
	ImportWallet(context.Context, *ImportWalletReq) (*ImportWalletRsp, error)
}

// UnimplementedGoWalletManageSvrServer should be embedded to have forward compatible implementations.
type UnimplementedGoWalletManageSvrServer struct {
}

func (UnimplementedGoWalletManageSvrServer) CreateWallet(context.Context, *CreateWalletReq) (*CreateWalletRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWallet not implemented")
}
func (UnimplementedGoWalletManageSvrServer) ImportWallet(context.Context, *ImportWalletReq) (*ImportWalletRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportWallet not implemented")
}

// UnsafeGoWalletManageSvrServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoWalletManageSvrServer will
// result in compilation errors.
type UnsafeGoWalletManageSvrServer interface {
	mustEmbedUnimplementedGoWalletManageSvrServer()
}

func RegisterGoWalletManageSvrServer(s grpc.ServiceRegistrar, srv GoWalletManageSvrServer) {
	s.RegisterService(&GoWalletManageSvr_ServiceDesc, srv)
}

func _GoWalletManageSvr_CreateWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWalletReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoWalletManageSvrServer).CreateWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go_wallet_manage_svr.go_wallet_manage_svr/CreateWallet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoWalletManageSvrServer).CreateWallet(ctx, req.(*CreateWalletReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoWalletManageSvr_ImportWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportWalletReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoWalletManageSvrServer).ImportWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go_wallet_manage_svr.go_wallet_manage_svr/ImportWallet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoWalletManageSvrServer).ImportWallet(ctx, req.(*ImportWalletReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GoWalletManageSvr_ServiceDesc is the grpc.ServiceDesc for GoWalletManageSvr service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoWalletManageSvr_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "go_wallet_manage_svr.go_wallet_manage_svr",
	HandlerType: (*GoWalletManageSvrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWallet",
			Handler:    _GoWalletManageSvr_CreateWallet_Handler,
		},
		{
			MethodName: "ImportWallet",
			Handler:    _GoWalletManageSvr_ImportWallet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "go_wallet_manage_svr.proto",
}
