// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: go_live_stream_svr.proto

// package 格式为服务进程名

package go_live_stream_svr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartLiveTaskReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId   string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	FilePath string `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	RtmpUrl  string `protobuf:"bytes,3,opt,name=rtmp_url,json=rtmpUrl,proto3" json:"rtmp_url,omitempty"`
}

func (x *StartLiveTaskReq) Reset() {
	*x = StartLiveTaskReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_live_stream_svr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartLiveTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLiveTaskReq) ProtoMessage() {}

func (x *StartLiveTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_go_live_stream_svr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLiveTaskReq.ProtoReflect.Descriptor instead.
func (*StartLiveTaskReq) Descriptor() ([]byte, []int) {
	return file_go_live_stream_svr_proto_rawDescGZIP(), []int{0}
}

func (x *StartLiveTaskReq) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StartLiveTaskReq) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *StartLiveTaskReq) GetRtmpUrl() string {
	if x != nil {
		return x.RtmpUrl
	}
	return ""
}

type StartLiveTaskRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *StartLiveTaskRsp) Reset() {
	*x = StartLiveTaskRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_live_stream_svr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartLiveTaskRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLiveTaskRsp) ProtoMessage() {}

func (x *StartLiveTaskRsp) ProtoReflect() protoreflect.Message {
	mi := &file_go_live_stream_svr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLiveTaskRsp.ProtoReflect.Descriptor instead.
func (*StartLiveTaskRsp) Descriptor() ([]byte, []int) {
	return file_go_live_stream_svr_proto_rawDescGZIP(), []int{1}
}

func (x *StartLiveTaskRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *StartLiveTaskRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UpdateLiveTaskReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId   string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	FilePath string `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	RtmpUrl  string `protobuf:"bytes,3,opt,name=rtmp_url,json=rtmpUrl,proto3" json:"rtmp_url,omitempty"`
}

func (x *UpdateLiveTaskReq) Reset() {
	*x = UpdateLiveTaskReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_live_stream_svr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLiveTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLiveTaskReq) ProtoMessage() {}

func (x *UpdateLiveTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_go_live_stream_svr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLiveTaskReq.ProtoReflect.Descriptor instead.
func (*UpdateLiveTaskReq) Descriptor() ([]byte, []int) {
	return file_go_live_stream_svr_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateLiveTaskReq) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *UpdateLiveTaskReq) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *UpdateLiveTaskReq) GetRtmpUrl() string {
	if x != nil {
		return x.RtmpUrl
	}
	return ""
}

type UpdateLiveTaskRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *UpdateLiveTaskRsp) Reset() {
	*x = UpdateLiveTaskRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_live_stream_svr_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLiveTaskRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLiveTaskRsp) ProtoMessage() {}

func (x *UpdateLiveTaskRsp) ProtoReflect() protoreflect.Message {
	mi := &file_go_live_stream_svr_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLiveTaskRsp.ProtoReflect.Descriptor instead.
func (*UpdateLiveTaskRsp) Descriptor() ([]byte, []int) {
	return file_go_live_stream_svr_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateLiveTaskRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateLiveTaskRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_go_live_stream_svr_proto protoreflect.FileDescriptor

var file_go_live_stream_svr_proto_rawDesc = []byte{
	0x0a, 0x18, 0x67, 0x6f, 0x5f, 0x6c, 0x69, 0x76, 0x65, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x5f, 0x73, 0x76, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x67, 0x6f, 0x5f, 0x6c,
	0x69, 0x76, 0x65, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x73, 0x76, 0x72, 0x22, 0x63,
	0x0a, 0x10, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4c, 0x69, 0x76, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52,
	0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66,
	0x69, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x74, 0x6d, 0x70,
	0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x74, 0x6d, 0x70,
	0x55, 0x72, 0x6c, 0x22, 0x38, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4c, 0x69, 0x76, 0x65,
	0x54, 0x61, 0x73, 0x6b, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x64, 0x0a,
	0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x76, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52,
	0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66,
	0x69, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x74, 0x6d, 0x70,
	0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x74, 0x6d, 0x70,
	0x55, 0x72, 0x6c, 0x22, 0x39, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x76,
	0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0xd1,
	0x01, 0x0a, 0x12, 0x67, 0x6f, 0x5f, 0x6c, 0x69, 0x76, 0x65, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x5f, 0x73, 0x76, 0x72, 0x12, 0x5b, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4c, 0x69,
	0x76, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x24, 0x2e, 0x67, 0x6f, 0x5f, 0x6c, 0x69, 0x76, 0x65,
	0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x73, 0x76, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x4c, 0x69, 0x76, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x24, 0x2e, 0x67,
	0x6f, 0x5f, 0x6c, 0x69, 0x76, 0x65, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x73, 0x76,
	0x72, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4c, 0x69, 0x76, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52,
	0x73, 0x70, 0x12, 0x5e, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x76, 0x65,
	0x54, 0x61, 0x73, 0x6b, 0x12, 0x25, 0x2e, 0x67, 0x6f, 0x5f, 0x6c, 0x69, 0x76, 0x65, 0x5f, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x73, 0x76, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x4c, 0x69, 0x76, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x25, 0x2e, 0x67, 0x6f,
	0x5f, 0x6c, 0x69, 0x76, 0x65, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x73, 0x76, 0x72,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x76, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52,
	0x73, 0x70, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x5a, 0x75, 0x6f, 0x46, 0x75, 0x68, 0x6f, 0x6e, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d,
	0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x2d, 0x70, 0x62, 0x2f, 0x67, 0x6f, 0x5f, 0x6c,
	0x69, 0x76, 0x65, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x73, 0x76, 0x72, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_go_live_stream_svr_proto_rawDescOnce sync.Once
	file_go_live_stream_svr_proto_rawDescData = file_go_live_stream_svr_proto_rawDesc
)

func file_go_live_stream_svr_proto_rawDescGZIP() []byte {
	file_go_live_stream_svr_proto_rawDescOnce.Do(func() {
		file_go_live_stream_svr_proto_rawDescData = protoimpl.X.CompressGZIP(file_go_live_stream_svr_proto_rawDescData)
	})
	return file_go_live_stream_svr_proto_rawDescData
}

var file_go_live_stream_svr_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_go_live_stream_svr_proto_goTypes = []interface{}{
	(*StartLiveTaskReq)(nil),  // 0: go_live_stream_svr.StartLiveTaskReq
	(*StartLiveTaskRsp)(nil),  // 1: go_live_stream_svr.StartLiveTaskRsp
	(*UpdateLiveTaskReq)(nil), // 2: go_live_stream_svr.UpdateLiveTaskReq
	(*UpdateLiveTaskRsp)(nil), // 3: go_live_stream_svr.UpdateLiveTaskRsp
}
var file_go_live_stream_svr_proto_depIdxs = []int32{
	0, // 0: go_live_stream_svr.go_live_stream_svr.StartLiveTask:input_type -> go_live_stream_svr.StartLiveTaskReq
	2, // 1: go_live_stream_svr.go_live_stream_svr.UpdateLiveTask:input_type -> go_live_stream_svr.UpdateLiveTaskReq
	1, // 2: go_live_stream_svr.go_live_stream_svr.StartLiveTask:output_type -> go_live_stream_svr.StartLiveTaskRsp
	3, // 3: go_live_stream_svr.go_live_stream_svr.UpdateLiveTask:output_type -> go_live_stream_svr.UpdateLiveTaskRsp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_go_live_stream_svr_proto_init() }
func file_go_live_stream_svr_proto_init() {
	if File_go_live_stream_svr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_go_live_stream_svr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartLiveTaskReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_live_stream_svr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartLiveTaskRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_live_stream_svr_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLiveTaskReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_live_stream_svr_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLiveTaskRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_go_live_stream_svr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_go_live_stream_svr_proto_goTypes,
		DependencyIndexes: file_go_live_stream_svr_proto_depIdxs,
		MessageInfos:      file_go_live_stream_svr_proto_msgTypes,
	}.Build()
	File_go_live_stream_svr_proto = out.File
	file_go_live_stream_svr_proto_rawDesc = nil
	file_go_live_stream_svr_proto_goTypes = nil
	file_go_live_stream_svr_proto_depIdxs = nil
}
